apiVersion: v1
kind: Service
metadata:
        name: prom-server
        labels:
                app: prometheus
spec:
        type: NodePort
        ports:
        - name: http
          nodePort: 30090
          port: 9090
          targetPort: 9090
        selector:
                app: prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: prom-pv-claim
        labels:
                app: prometheus
spec:
        accessModes:
        - ReadWriteOnce
        resources:
                requests:
                        storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: prom-server
        labels:
                app: prometheus
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: prometheus
        template:
                metadata:
                        labels:
                                app: prometheus
                spec:
                        containers:
                        - name: prom-con
                          image: saurabh43800/prometheus:v2
                          volumeMounts:
                          - name: prom-persistent-storage
                            mountPath: /prometheus/
                        volumes:
                        - name: prom-persistent-storage
                          persistentVolumeClaim:
                                  claimName: prom-pv-claim
